apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: strategic-swallow-go
  janus-idp.io/tekton: strategic-swallow-go
  backstage.io/kubernetes-id: strategic-swallow-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: strategic-swallow-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
